"""
Django settings for canteen project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-71l2$9wey-99imvl5i44&b0byeo7_&$6y*#-f^ln5f0)p2tvsr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'authentication',
    'cart',
    'checkout',
    'webpush',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'canteen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                "cart.context_processors.cart_count",
            ],
        },
    },
]

WSGI_APPLICATION = 'canteen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR /'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'authentication.CustomUser'


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store session in DB
SESSION_COOKIE_AGE = 86400  # Session lasts 1 day
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after closing the browser

LOGIN_URL = '/user_login/'  # Redirects unauthorized users to this page

RAZORPAY_KEY_ID = "rzp_test_SKA7pG9S47EI84"
RAZORPAY_KEY_SECRET = "ATnSwK9297SQ9AyevVPxANWC"
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": """-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoEtv+yTf7UkBtXCi2OPM5s5u/Um0
fbBD9iAZ+c70gH970ujwDFaLnOjtwpbD5aj9p4Qo8uVpl7QKdpVwmsyVfQ==
-----END PUBLIC KEY-----""",
    
    "VAPID_PRIVATE_KEY": """-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgCxnGPNZutzDLi1OA
LzTomRr80xICKuZXFZtgGw22niyhRANCAASgS2/7JN/tSQG1cKLY48zmzm79SbR9
sEP2IBn5zvSAf3vS6PAMVouc6O3ClsPlqP2nhCjy5WmXtAp2lXCazJV9
-----END PRIVATE KEY-----""",
    
    "VAPID_ADMIN_EMAIL": "nazeemdath.1@gmail.com"
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nazeemdath@gmail.com'           # Your Gmail address
EMAIL_HOST_PASSWORD = 'gqlnlpqncrrnzzvn'        # App Password from Google
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'smart-canteen-620w.onrender.com'
]


