# Generated by Django 5.1.7 on 2025-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('ready', 'Ready for Pickup'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
