# Generated by Django 5.1.7 on 2025-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_feedback_options_alter_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
