# Generated by Django 5.1.7 on 2025-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mealsubscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsubscriptionplan',
            name='meals_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remaining_meals',
            field=models.IntegerField(default=0),
        ),
    ]
