# Generated by Django 5.1.7 on 2025-03-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mealsubscriptionplan_meals_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubscriptionMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_available', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_on', models.DateTimeField(auto_now_add=True)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersubscription')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscriptionmeal')),
            ],
        ),
    ]
