# Generated by Django 5.1.7 on 2025-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usersubscription_active_subscriptionmeal_claimedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
