# Generated by Django 5.1.7 on 2025-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_order'),
        ('main', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products for this coupon', to='main.product'),
        ),
    ]
