# Generated by Django 5.1.7 on 2025-03-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_coupon_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
